/*================================================================================*/
/* DDL SCRIPT                                                                     */
/*================================================================================*/
/*  Title    :                                                                    */
/*  FileName : sistema_escolar.ecm                                                         */
/*  Platform : PostgreSQL 9.4                                                     */
/*  Version  : Concept                                                            */
/*  Date     : sexta-feira, 4 de dezembro de 2015                                 */
/*================================================================================*/
/*================================================================================*/
/* CREATE TABLES                                                                  */
/*================================================================================*/

CREATE TABLE ALUNO (
  ID_ALUNO SERIAL,
  TX_NOME VARCHAR(60) NOT NULL,
  TX_MATRICULA VARCHAR(10) NOT NULL,
  DT_NASCIMENTO DATE NOT NULL,
  TX_EMAIL VARCHAR(256),
  DT_CADASTRO TIMESTAMP NOT NULL,
  CONSTRAINT PK_ALUNO PRIMARY KEY (ID_ALUNO)
);

CREATE TABLE PERIODO_LETIVO (
  ID_PERIODO_LETIVO SERIAL,
  TX_DESCRICAO VARCHAR(54) NOT NULL,
  NB_ANO INTEGER NOT NULL,
  CS_ATIVO BOOLEAN NOT NULL,
  CONSTRAINT PK_PERIODO_LETIVO PRIMARY KEY (ID_PERIODO_LETIVO)
);

CREATE TABLE TURMA (
  ID_TURMA SERIAL,
  ID_PERIODO_LETIVO INTEGER NOT NULL,
  TX_DESCRICAO VARCHAR(54),
  CONSTRAINT PK_TURMA PRIMARY KEY (ID_TURMA)
);

CREATE TABLE MODULO (
  ID_MODULO SERIAL,
  TX_DESCRICAO VARCHAR(54) NOT NULL,
  CS_ATIVO BOOLEAN NOT NULL,
  DT_CADASTRO TIMESTAMP DEFAULT NOW() NOT NULL,
  CONSTRAINT PK_MODULO PRIMARY KEY (ID_MODULO)
);

CREATE TABLE MATRICULA (
  ID_MATRICULA SERIAL,
  DT_MATRICULA TIMESTAMP NOT NULL,
  ID_PERIODO_LETIVO INTEGER NOT NULL,
  ID_ALUNO INTEGER NOT NULL,
  ID_MODULO INTEGER NOT NULL,
  CS_SITUACAO CHAR(1),
  CONSTRAINT PK_MATRICULA PRIMARY KEY (ID_MATRICULA)
);

ALTER TABLE MATRICULA 
ADD CONSTRAINT CHECK_CS_SITUACAO CHECK ( CS_SITUACAO IN ('A', 'I', 'C') );

COMMENT ON COLUMN MATRICULA.CS_SITUACAO IS
'A - ATIVA, I - INATIVA, C - CANCELADA';

CREATE TABLE ALUNOS_TURMA (
  ID_ALUNOS_TURMA SERIAL,
  ID_TURMA INTEGER NOT NULL,
  ID_MATRICULA INTEGER NOT NULL,
  CONSTRAINT PK_ALUNOS_TURMA PRIMARY KEY (ID_ALUNOS_TURMA)
);

CREATE TABLE DISCIPLINA (
  ID_DISCIPLINA SERIAL NOT NULL,
  TX_NOME VARCHAR(54) NOT NULL,
  CS_ATIVO BOOLEAN NOT NULL,
  DT_CADASTRO TIMESTAMP DEFAULT NOW() NOT NULL,
  ID_MODULO INTEGER NOT NULL,
  CONSTRAINT PK_DISCIPLINA PRIMARY KEY (ID_DISCIPLINA)
);

CREATE TABLE LANCAMENTO_NOTA (
  ID_LANCAMENTO_NOTA SERIAL,
  ID_MATRICULA INTEGER NOT NULL,
  ID_TURMA INTEGER NOT NULL,
  ID_DISCIPLINA INTEGER NOT NULL,
  NB_NOTA1 NUMERIC(3,1) CHECK (NB_NOTA1 BETWEEN 0 AND 10),
  NB_NOTA2 NUMERIC(3,1) CHECK (NB_NOTA2 BETWEEN 0 AND 10),
  NB_NOTA3 NUMERIC(3,1) CHECK (NB_NOTA3 BETWEEN 0 AND 10),
  NB_NOTA4 NUMERIC(3,1) CHECK (NB_NOTA4 BETWEEN 0 AND 10),
  CONSTRAINT PK_LANCAMENTO_NOTA PRIMARY KEY (ID_LANCAMENTO_NOTA)
);

/*================================================================================*/
/* CREATE INDEXES                                                                 */
/*================================================================================*/
 
CREATE UNIQUE INDEX IDX_ALUNO_TX_MATRICULA ON ALUNO (TX_MATRICULA);

CREATE UNIQUE INDEX IDX_PERIODO_LETIVO ON PERIODO_LETIVO (NB_ANO);

CREATE UNIQUE INDEX IDX_TURMA ON TURMA (TX_DESCRICAO);

CREATE UNIQUE INDEX IDX_MODULO_TX_DESCRICAO ON MODULO (TX_DESCRICAO);

CREATE UNIQUE INDEX IDX_DISCIPLICA ON DISCIPLINA (TX_NOME, ID_MODULO);

/*================================================================================*/
/* CREATE FOREIGN KEYS                                                            */
/*================================================================================*/

ALTER TABLE TURMA
  ADD CONSTRAINT FK_TURMA_PERIODO_LETIVO
  FOREIGN KEY (ID_PERIODO_LETIVO) REFERENCES PERIODO_LETIVO (ID_PERIODO_LETIVO);

ALTER TABLE MATRICULA
  ADD CONSTRAINT FK_MATRICULA_ALUNO
  FOREIGN KEY (ID_ALUNO) REFERENCES ALUNO (ID_ALUNO);

ALTER TABLE MATRICULA
  ADD CONSTRAINT FK_MATRICULA_MODULO
  FOREIGN KEY (ID_MODULO) REFERENCES MODULO (ID_MODULO);

ALTER TABLE MATRICULA
  ADD CONSTRAINT FK_MATRICULA_PERIODO_LETIVO
  FOREIGN KEY (ID_PERIODO_LETIVO) REFERENCES PERIODO_LETIVO (ID_PERIODO_LETIVO);

ALTER TABLE ALUNOS_TURMA
  ADD CONSTRAINT FK_MATRICULA_TURMA_TURMA
  FOREIGN KEY (ID_TURMA) REFERENCES TURMA (ID_TURMA);

ALTER TABLE ALUNOS_TURMA
  ADD CONSTRAINT FK_MATRICULA_TURMA_MATRICULA
  FOREIGN KEY (ID_MATRICULA) REFERENCES MATRICULA (ID_MATRICULA);

ALTER TABLE DISCIPLINA
  ADD CONSTRAINT FK_DISCIPLINA_MODULO
  FOREIGN KEY (ID_MODULO) REFERENCES MODULO (ID_MODULO);

ALTER TABLE LANCAMENTO_NOTA
  ADD CONSTRAINT FK_LANCAMENTO_NOTA_MATRICULA
  FOREIGN KEY (ID_MATRICULA) REFERENCES MATRICULA (ID_MATRICULA);

ALTER TABLE LANCAMENTO_NOTA
  ADD CONSTRAINT FK_LANCAMENTO_NOTA_DISCIPLINA
  FOREIGN KEY (ID_DISCIPLINA) REFERENCES DISCIPLINA (ID_DISCIPLINA);

ALTER TABLE LANCAMENTO_NOTA
  ADD CONSTRAINT FK_LANCAMENTO_NOTA_TURMA
  FOREIGN KEY (ID_TURMA) REFERENCES TURMA (ID_TURMA);

